INSERT_MOVIE = '''
    INSERT INTO MOVIE (NAME, RATING)
    VALUES (?,?);
'''

INSERT_PROJECTION = '''
    INSERT INTO PROJECTION (MOVIE_ID, TYPE, DATE)
    VALUES (?, ?, ?, ?);
'''

INSERT_RESERVATION = '''
    INSERT INTO RESERVATION (USER_ID, PROJECTION_ID, ROW, COL)
    VALUES (?, ?, ?, ?);
'''

INSERT_USER = '''
    INSERT INTO USER(USERNAME, PASSWORD, ACTIVE)
    VALUES (?, ?, ?)
'''
