SELECT_MOVIES_ORDERED_BY_RATING = '''
    SELECT *
    FROM MOVIE
    ORDER BY RATING;
'''

SELECT_PROJECTION_FOR_MOVIE = '''
    SELECT p.*, COUNT(r.ROW * r.COL)
    FROM PROJECTION as p
    LEFT JOIN RESERVATION as r
    ON r.PROJECTION_ID = p.ID
    WHERE p.MOVIE_ID = ?
    GROUP BY p.ID
    ORDER BY p.DATE;
'''


SELECT_PROJECTION_ORDERED_BY_DATE = '''
    SELECT PROJECTION.*, COUNT(RESERVATION.ROW * RESERVATION.COL)
    FROM PROJECTION
    LEFT JOIN RESERVATION
    ON RESERVATION.PROJECTION_ID = PROJECTION.ID
    WHERE PROJECTION.MOVIE_ID = ? AND PROJECTION.DATE BETWEEN ? AND ?
    GROUP BY PROJECTION.ID
    ORDER BY PROJECTION.DATE;
'''

IS_USER_IN_USERS = '''
    SELECT *
    FROM USER
    WHERE USERNAME = ? and PASSWORD LIKE ?;
'''

SELECT_AVAILABLE_SEATS = '''
    SELECT ROW, COL
    FROM RESERVATION
    WHERE PROJECTION_ID = ? AND ROW IS NOT NULL AND COL IS NOT NULL;
'''

SELECT_PROJECTION_BY_ID = '''
    SELECT *
    FROM PROJECTION as p
    WHERE p.ID = ?
'''

SELECT_MOVIE_BY_ID = '''
    SELECT *
    FROM MOVIE as m
    WHERE m.ID = ?
'''

SELECT_RESERVATIONS_FOR_USER = '''
    SELECT m.NAME, r.ROW, r.COL
    FROM RESERVATION AS r
    INNER JOIN USER AS u
    ON r.USER_ID = u.ID AND u.ID = ?
    INNER JOIN PROJECTION as p
    ON p.ID = r.PROJECTION_ID
    INNER JOIN MOVIE as m
    ON m.ID = p.MOVIE_ID
'''
