SELECT_MOVIES_ORDERED_BY_RATING = '''
    SELECT *
    FROM MOVIE
    ORDER BY RATING;
'''

SELECT_PROJECTION_FOR_MOVIE = '''
    SELECT p.*, COUNT(r.ROW * r.COL)
    FROM PROJECTION as p
    LEFT JOIN RESERVATION as r
    ON r.PROJECTION_ID = p.ID
    WHERE p.MOVIE_ID = ?
    GROUP BY p.ID
    ORDER BY p.DATE;
'''


SELECT_PROJECTION_ORDERED_BY_DATE = '''
    SELECT PROJECTION.*, COUNT(RESERVATION.ROW * RESERVATION.COL)
    FROM PROJECTION
    LEFT JOIN RESERVATION
    ON RESERVATION.PROJECTION_ID = PROJECTION.ID
    WHERE PROJECTION.MOVIE_ID = ? AND PROJECTION.DATE BETWEEN ? AND ?
    GROUP BY PROJECTION.ID
    ORDER BY PROJECTION.DATE;
'''

IS_USER_IN_USERS = '''
    SELECT *
    FROM USERS
    WHERE USERNAME = ? and PASSWORD LIKE ?;
'''

SELECT_AVAILABLE_SEATS = '''
    SELECT ROW, COL
    FROM RESERVATIONS
    WHERE PROJECTION_ID = ? AND ROW IS NOT NULL AND COL IS NOT NULL;
'''
