UPDATE_MOVIE = '''
    UPDATE MOVIE
    SET column1=?, RATING=?
    WHERE MOVIE.ID=?;
'''

UPDATE_PROJECTION = '''
    UPDATE PROJECTION
    SET MOVIE_ID=?, TYPE=?, DATE=?
    WHERE PROJECTION.ID=?;
'''
